# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: PulumiCsharpCurrentImage
version: 1.0.0
summary: Pulumi C# Environment
description: Deploys a Storage Account with Pulumi in C#
runner: pulumi/azure-deployment-environments:0.1.0
templatePath: Pulumi.yaml

parameters:
  - id: sku
    name: SKU Name
    description: Storage account SKU name.
    type: string
    required: false
    default: Standard_LRS
